### ISSUE TITLE
No snap-ins have been registered for Windows PowerShell version 4

### ISSUE THREAD

**Issue by Robert-M-Green** [aws-quickstart/quickstart-microsoft-exchange#16]
Other than changing the net addresses etc. I am running the exchange quick start mostly right out of the box. I had it working fine the other day and then when I went to the various GitHub sites to grab the latest scripts so that they would launch from my S3 instead of hitting the microsoftquickstart S3 bucket I run into this:
16:26:05 UTC-0600	CREATE_FAILED	AWS::CloudFormation::WaitCondition	ExchangeNode2WaitCondition	WaitCondition received failed message: 'Command failure in C:\cfn\scripts\Configure-ExchangeDAG.ps1 on line 91 Exception: System.Management.Automation.RemoteException: No snap-ins have been registered for Windows PowerShell version 4.' for uniqueId: i-0110313f7d7d8080c

Do I have a mismatched AMI maybe? or a script error not yet rolled out? This maybe an easy fix as my Exchange and PowerShell mojo is still weak. I come from a linux aws world afterall.
Thanks,
Robert

**Comment by Robert-M-Green** [comment]
It's not an AMI mismatch from my latest round of testing.

**Comment by dragos-madarasan** [comment]
Are you getting the error just on ExchangeNode2? Can you check whether Exchange gets installed successfully? Check the logs under C:\ExchangeInstall. 

The error likely fails due to the Exchange snappin not being there, e.g. likely [this](https://github.com/aws-quickstart/quickstart-microsoft-exchange/blob/master/scripts/Configure-ExchangeDAG.ps1#L60)

**Comment by Robert-M-Green** [comment]
just did a full clean of my stacks and figured lets try to run this with 3 nodes to see if the order/timing changes results. Node 2 still fails Node1 Node3 both come up nicely. Of course it is Node2 that has the extra logic to establish the DAG configuration. Error message was simular but different this time:
14:52:43 UTC-0600	CREATE_FAILED	AWS::CloudFormation::WaitCondition	ExchangeNode2WaitCondition	WaitCondition received failed message: 'Command failure in C:\cfn\scripts\Configure-ExchangeDAG.ps1 on line 91 Exception: System.Management.Automation.RemoteException: The Microsoft Exchange Replication service does not appear to be running on exchangenode1. Make sure that the server is op...'

**Comment by Robert-M-Green** [comment]
My guese would be the issue and the difference has to do with this:
$ConfigDAG={
        $ErrorActionPreference = "Stop"

        Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
        New-DatabaseAvailabilityGroup -Name $Using:DAGName -WitnessServer $Using:FileServerNetBIOSName -WitnessDirectory C:\$Using:DAGName -DatabaseAvailabilityGroupIpAddresses '255.255.255.255'
        
        Start-Sleep -s 60

        Add-DatabaseAvailabilityGroupServer -Identity $Using:DAGName -MailboxServer $Using:ExchangeNode1NetBIOSName
        Add-DatabaseAvailabilityGroupServer -Identity $Using:DAGName -MailboxServer $Using:ExchangeNode2NetBIOSName

        # Manuall run
        #Add-MailboxDatabaseCopy -Identity DB1 -MailboxServer $Using:ExchangeNode2NetBIOSName -ActivationPreference 2
        #Add-MailboxDatabaseCopy -Identity DB2 -MailboxServer $Using:ExchangeNode1NetBIOSName -ActivationPreference 2

        #There should also be a restart of the IS service (restart-service MSExchangeIS on each node)
        #Get-MailboxDatabaseCopyStatus * | where {$_.ContentIndexState -eq "Failed"} | Update-MailboxDatabaseCopy -CatalogOnly

    }
    if ($ExchangeNode3NetBIOSName) {
        $ConfigDAG={
            $ErrorActionPreference = "Stop"
            
            Add-PSSnapin Microsoft.Exchange.Management.PowerShell.SnapIn
            New-DatabaseAvailabilityGroup -Name $Using:DAGName -WitnessServer $Using:ExchangeNode3NetBIOSName -WitnessDirectory C:\$Using:DAGName
            
            Start-Sleep -s 60

            Add-DatabaseAvailabilityGroupServer -Identity $Using:DAGName -MailboxServer $Using:ExchangeNode1NetBIOSName
            Add-DatabaseAvailabilityGroupServer -Identity $Using:DAGName -MailboxServer $Using:ExchangeNode2NetBIOSName
        }
    }

**Comment by dragos-madarasan** [comment]
Hi @Robert-M-Green , are you still seeing this come up? I've not seen this issue in our CI tests for a while now.
