### ISSUE TITLE
API: ec2:RunInstances Not authorized for images: [ami-033df17da30f7ea72]

### ISSUE THREAD

**Issue by iruleDJ** [aws-quickstart/quickstart-microsoft-exchange#17]
When attempting to create the exchange stack on a new VPC I'm getting these 2 errors on ExchangeNode1 and FileServer:
API: ec2:RunInstances Not authorized for images: [ami-033df17da30f7ea72]
API: ec2:RunInstances Not authorized for images: [ami-09d7f402df5fd27aa]

I'm guessing this is because the Windows Server AMI was updated recently, but hasn't been added to the template yet.

Just curious if there is a timeframe on the update for this, or if there is anything I can change manually to get this to work.

**Comment by dragos-madarasan** [comment]
Hi,

Thanks for bringing this to our attention, we are in the process of updating the AMI and making the necessary adjustments. In the meantime, cloning the repository and manually changing the AMIs would be a potential workaround.

**Comment by Artanor** [comment]
Just hit this same issue.  Which ami is it supposed to be so i can do the clone and manual update?

**Comment by Artanor** [comment]
OK cloning the repo and editing the ami's doesnt work as this is no longer compatible with the active directory quickstart either. I tried reverting the AD template in that but then hit another issue where the ad template get stuck on a wait condition for the DC's and eventually times out.  I have now spent more time trying to fix the automation of this than I would have building it from scratch!

**Comment by virtlima** [comment]
Update has been merged that Uses SSM Param for AMIs, also uses Secrets manager

**Comment by laurablockchain** [comment]
> Hi,
> 
> Thanks for bringing this to our attention, we are in the process of updating the AMI and making the necessary adjustments. In the meantime, cloning the repository and manually changing the AMIs would be a potential workaround.

Hi Dragos, I am also having a similar error with the following aws template https://github.com/vu-h-le/pbi-aws 
Are you able to advise how I can manually update the AMIs please if this will solve the issue?

Many Thanks, Laura

**Comment by laurablockchain** [comment]
Actually no worries. I've now solved the issue by cloning the code, editing and saving with updated AMIs which I found by following the following instructions https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html
