### ISSUE TITLE
Exchange 2013 download URL for CU21 is no longer valid

### ISSUE THREAD

**Issue by ratsputin** [aws-quickstart/quickstart-microsoft-exchange#20]
In line 628 of the exchange.template, the following line defines the download link for Exchange 2013:
```
 '2013': https://download.microsoft.com/download/9/4/1/94166586-5D17-414A-97DA-CCD069BC11A2/Exchange2013-x64-cu21.exe
```
This URL is no longer valid.  The current rollup is cu23 at:
```
https://download.microsoft.com/download/7/F/D/7FDCC96C-26C0-4D49-B5DB-5A8B36935903/Exchange2013-x64-cu23.exe
```

**Comment by dragos-madarasan** [comment]
Hi @ratsputin, thanks for bringing this to our attention. Given the latest CUs also support .Net Framework 4.8 this might be something I'd like to add so need to do a bit of testing.

**Comment by dragos-madarasan** [comment]
This has been fixed in https://github.com/aws-quickstart/quickstart-microsoft-exchange/commit/05b7cf6684f7984ca922126db7fc3831adedbe38, thank you.
