### ISSUE TITLE
CIDR block parameter must be in the form x.x.x.x/x 

### ISSUE THREAD

**Issue by ZeevX43** [aws-quickstart/quickstart-microsoft-exchange#25]
HI,

While creating a stack, itt fails with the error: Parameter RDGWCIDR failed to satisfy constraint: CIDR block parameter must be in the form x.x.x.x/x 

Any idea on how to solve it?

thanks

**Comment by dragos-madarasan** [comment]
Hi, you likely have used a blank value for RDGWCIDR. It needs to be in a format similar to "10.0.0.0/16". You can read more about VPC fundamentals [here](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.htm).
