### ISSUE TITLE
TMP files in C:\Windows\Temp on Exchange mailbox servers

### ISSUE THREAD

**Issue by rosenbluh** [aws-quickstart/quickstart-microsoft-exchange#27]
At least for Exchange 2016, the C:\Windows\Temp folder fills up on Exchange mailbox servers deployed via this QuickStart. The log files show errors with Unified Messaging. In Services.msc the Unified Messaging service keeps  attempting to start.

Would it be possible to disable the installation of the Unified Messaging service or to at least provide the option in the template to do so?

**Comment by rosenbluh** [comment]
Here is an example of one of the Windows logs (event 1038 in the Windows Application log):



	The Microsoft Exchange Unified Messaging service wasn't able to start. More information: "System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Rtc.Collaboration, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
	File name: 'Microsoft.Rtc.Collaboration, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
	   at Microsoft.Exchange.UM.UMService.UMConnectionManagerHelper.TCPConnectionManager.Initialize()
	   at Microsoft.Exchange.UM.UMService.UMConnectionManagerHelper.MultiConnectionManager.Initialize()
	   at Microsoft.Exchange.UM.UMService.UMService.InitializeConnectionManager()
	   at Microsoft.Exchange.UM.UMService.UMService.InternalStart()
	   at Microsoft.Exchange.UM.UMCore.UMServiceBase.StartService()
	   at Microsoft.Exchange.UM.UMCore.UMServiceBase.OnStartInternal(String[] args)

	WRN: Assembly binding logging is turned OFF.
	To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
	Note: There is some performance penalty associated with assembly bind failure logging.
	To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
	"

**Comment by dragos-madarasan** [comment]
Hi @rosenbluh, thanks for raising this; does the Exchange installation log report a successful installation?

**Comment by rosenbluh** [comment]
I see the following line in the ExchangeSetup.log file that suggests it completes successfully, but I am not very familiar with this log file. I've redacted the domain and username in the full file so it can be uploaded.

	[10/30/2019 08:17:51.0020] [1] Processing component 'Unified Messaging PostSetup' (Finalizing Setup for Mailbox role: Unified Messaging service).
	[10/30/2019 08:17:51.0020] [1] Executing (non-critical): 
		start-SetupService -ServiceName MSExchangeUM

**Comment by rosenbluh** [comment]
Please see the attached log file.

[ExchangeSetup.log](https://github.com/aws-quickstart/quickstart-microsoft-exchange/files/3816908/ExchangeSetup.log)

**Comment by rosenbluh** [comment]
I should have mentioned this initially but I have attempted multiple deploys of this QuickStart in the past few weeks and they have all had this problem.
