### ISSUE TITLE
Rollback occurring due to failed edge node deployment

### ISSUE THREAD

**Issue by rosenbluh** [aws-quickstart/quickstart-microsoft-exchange#29]
Multiple attempts in the last 24 hours to perform the deployment failed due to an issue with the Edge nodes. This is the first error that appears in the CloudFormation log is this for the ExchangeStack:

	WaitCondition received failed message: 'Command failure in C:\cfn\scripts\Install-ExchangeEdgeServer.ps1 on line 44 Exception: System.Management.Automation.RemoteException: This command cannot be run due to the error: The system cannot find the file specified.' for uniqueId: i-0d1dd0403e9f05efe

Line 44 is:

	Invoke-Command -Authentication Credssp -Scriptblock $InstallExchPs -ComputerName $env:COMPUTERNAME -Credential $LocalAdminCreds

I verified that the values for EdgeNode1NetBIOSName and EdgeNode1NetBIOSName were the default values.

This is in the us-west-2 region.

Please let me know if any other information is needed to troubleshoot this.

**Comment by dragos-madarasan** [comment]
@rosenbluh we updated the Quickstart to fix some issues we were seeing. Can you see if you can replace the behaviour with the newer version?
