### ISSUE TITLE
Parameter validation failed - AvailabilityZones

### ISSUE THREAD

**Issue by dyleroo** [aws-quickstart/quickstart-microsoft-exchange#37]
Before the stack can create I receive this error:

`Error: CREATE_FAILED: ["Parameter validation failed: parameter value eu-north-1a for parameter name AvailabilityZones does not exist, parameter value eu-north-1b for parameter name AvailabilityZones does not exist"]`

Error returning when using this template during CI via Jenkins. This works locally but there is not much information online on why this is happening or how to resolve.

I have attempted to use other availability zones to no avail.

**Comment by dragos-madarasan** [comment]
Are you running the template in the Europe (Stockholm) region? If so that should work. How are you generating the AZs to use via Jenkins?

**Comment by dyleroo** [comment]
Hi, the Jenkins file is simply running a rake task that setups the cloud formation stack using terraform.

It works locally but not during this CI process. Is this a credentials issue?

**Comment by dyleroo** [comment]
Hi Dragos, this was a credential issue resolved by updating my AWS credentials.
