### ISSUE TITLE
Error in script for Canada central region

### ISSUE THREAD

**Issue by mithun008** [aws-quickstart/quickstart-microsoft-exchange#5]
I get the following error when running the quick start for existing VPC in Canada central region.
'Command failure in C:\cfn\scripts\Create-Folder.ps1 on line 22 Exception: System.Management.Automation.RemoteException: An item with the specified name C:\exchinstall already exists.' for uniqueId: i-076ea9009f88b7bdf

It worked fine in the us-west-1 region.

**Comment by dragos-madarasan** [comment]
I am closing out this issue since we've released several new versions since then. Please re-open it if you are encountering any issue.
