### ISSUE TITLE
Any plans to upgrade this to support Exchange 2016?

### ISSUE THREAD

**Issue by robrant** [aws-quickstart/quickstart-microsoft-exchange#7]
(Sorry for using an issue to ask this)
We're thinking about using this to deploy an Exchange test environment, but we'd like to use Exchange 2016. Do you have any plans to do that as part of this project or if not, is there anything we should watch for in having a go? 
Thanks!

**Comment by virtlima** [comment]
Yes we have plans on reviewing and updating all MSFT Quick Starts. Please feel free to modify as needed and make a pull request.

**Comment by robrant** [comment]
Will do, although it may not be any time soon in our case - there's some background learning/understanding required on the differences between 2013 and 2016 we'd need to address first. We'd be really interested in road testing it (and providing beer) for anyone that gets there before us.

**Comment by Fishbowler** [comment]
I've been trying this, but scuppered by https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/issues/15

**Comment by Fishbowler** [comment]
Using my own branch with a fix for that (there's a PR at https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/pull/20), I think I've got a working environment. Testing it today.

**Comment by virtlima** [comment]
We have released support for Exchange 2016 now, going to close this out.
