### ISSUE TITLE
Feature: Provide option to deploy without edge nodes

### ISSUE THREAD

**Issue by rosenbluh** [aws-quickstart/quickstart-microsoft-exchange#81]
This feature request is to deploy without edge nodes or to allow for non-Edge nodes to receive and send email directly from the internet. On a deployment using this template I had to bypass the edge nodes due to restrictions on relaying messages. Also, edge nodes are also difficult to manage and add additional cost to the deployment. It seems that the only advantage to edge nodes is that it in theory protects against a deployment where ports 25 or 587 are exposed to the entire internet AND a bug is discovered that allows an Exchange server to become compromised purely from SMTP traffic. Most, maybe almost all, Exchange deployments these days are firewalled to only allow SMTP traffic inbound from specific IP ranges (anti-spam service, application, partner organization, etc), so the edge node deployment really is an edge case for very large Exchange deployments.

**Comment by dragos-madarasan** [comment]
hi @rosenbluh , the Quickstart does allow a deployment without the Edge nodes, this is controllable by the parameter **IncludeEdgeTransportRole** and by default it is not selected.
